name: dart validation

on:
  pull_request:

env:
  FLUTTER_VERSION: '3.29.2' # Обери потрібну версію

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run Dart Analysis
        uses: invertase/github-action-dart-analyzer@main
        with:
          fatal-infos: true
